#! /bin/sh
_PWD=`pwd`
_APPNAME=runJMXMiniProbe
echo Installing $_APPNAME ...
ln -s $_PWD/bin/$_APPNAME /etc/init.d/$_APPNAME
#update-rc.d $_APPNAME start 20 3 5 . stop 20 0 1 2 4 6 .
# configure chkconfig install
if [ -x /sbin/chkconfig ]; then
	/sbin/chkconfig --add $_APPNAME
else
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc3.d/S20$_APPNAME
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc5.d/S20$_APPNAME

	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc0.d/K10$_APPNAME
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc1.d/K10$_APPNAME
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc2.d/K10$_APPNAME
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc4.d/K10$_APPNAME
	ln -sf /etc/init.d/$_APPNAME /etc/rc.d/rc6.d/K10$_APPNAME
fi
 