#! /bin/sh
_PWD=`pwd`
_APPNAME=runJMXMiniProbe
echo Removing $_APPNAME ...

#chkconfig scripts removal
#only on uninstall, not on upgrades.
if [ $1 = 0 ]; then
	/etc/init.d/$_APPNAME stop
	if [ -x /sbin/chkconfig ]; then
		echo "chkconfig --del $_APPNAME"
		/sbin/chkconfig --del $_APPNAME
	else
		echo "Deleting /etc/rc.d/rc?.d/???$_APPNAME"
		rm -f /etc/rc.d/rc?.d/???$_APPNAME
	fi
fi
###################################
echo "Deleting /etc/init.d/$_APPNAME"
rm /etc/init.d/$_APPNAME
echo $_APPNAME is Successfully Removed!
